name: Python Backend API

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
    
        env:
            CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
            PASSWORD: ${{ secrets.PASSWORD }}
            NAME: ${{ secrets.NAME }}
        run: |
          pytest test/techstack_test.py
          pytest test/techstack_metadata_test.py
